export const languageRules = {
  python: {
    semicolon: false,
    indentation: true,
    checkUndefined: true,
    commentRegex: /^#/,
    varDeclarationRegex: /\b(\w+)\s*=/,
    builtIns: [
      "print",
      "len",
      "range",
      "int",
      "float",
      "str",
      "list",
      "dict",
      "set",
      "input",
      "type",
      "sum",
      "map",
      "zip",
      "filter",
      "open",
      "close",
    ],
    syntaxPatterns: [],
  },

  java: {
    semicolon: true,
    indentation: false,
    checkUndefined: true,
    commentRegex: /^\/\//,
    varDeclarationRegex: /\b(int|float|double|String|char|boolean)\s+(\w+)/,
    builtIns: ["System", "out", "println", "main", "String", "Integer", "Math"],
    syntaxPatterns: [],
    reservedKeywords: [
      "if",
      "else",
      "while",
      "for",
      "switch",
      "case",
      "break",
      "continue",
      "return",
      "int",
      "float",
      "double",
      "char",
      "void",
      "class",
      "public",
      "private",
      "protected",
      "static",
      "final",
      "try",
      "catch",
      "new",
      "delete",
      "this",
      "super",
      "true",
      "false",
    ],
  },

  c: {
    semicolon: true,
    indentation: false,
    checkUndefined: true,
    commentRegex: /^\/\//,
    varDeclarationRegex: /\b(int|float|double|char|void)\s+(\w+)/,
    builtIns: ["printf", "scanf", "main", "return", "sizeof"],
    syntaxPatterns: [],
    reservedKeywords: [
      "if",
      "else",
      "while",
      "for",
      "switch",
      "case",
      "break",
      "continue",
      "return",
      "int",
      "float",
      "double",
      "char",
      "void",
      "class",
      "public",
      "private",
      "protected",
      "static",
      "final",
      "try",
      "catch",
      "new",
      "delete",
      "this",
      "super",
      "true",
      "false",
    ],
  },

  cpp: {
    semicolon: true,
    indentation: false,
    checkUndefined: true,
    commentRegex: /^\/\//,
    varDeclarationRegex: /\b(int|float|double|string|char|bool|void)\s+(\w+)/,
    builtIns: ["cout", "cin", "endl", "std", "main", "return"],
    syntaxPatterns: [],
    reservedKeywords: [
      "if",
      "else",
      "while",
      "for",
      "switch",
      "case",
      "break",
      "continue",
      "return",
      "int",
      "float",
      "double",
      "char",
      "void",
      "class",
      "public",
      "private",
      "protected",
      "static",
      "final",
      "try",
      "catch",
      "new",
      "delete",
      "this",
      "super",
      "true",
      "false",
    ],
  },
};
